=== SimonMarcell/K9IVJV_XMLGyak/XMLTaskK9IVJV/DOMParseK9IVJV/src/XMLSchemaK9IVJV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="qualified">

    <!--Egyszerű elemek definíciói-->
    <xs:element name="nev" type="xs:string"/>
    <xs:element name="szuletesihely" type="xs:string"/>
    <xs:element name="szuletesiido" type="xs:date"/>
    <xs:element name="allampolgarsag" type="xs:string"/>
    <xs:element name="alapitaseve" type="xs:integer"/>
    <xs:element name="edzo" type="xs:string"/>
    <xs:element name="helyezes" type="xs:integer"/>
    <xs:element name="sportag" type="xs:string"/>
    <xs:element name="helyszin" type="xs:string"/>
    <xs:element name="datum" type="xs:date"/>

    <!--Attribútumok definíciói-->
    <xs:attribute name="jatekos_ID" type="xs:integer"/>
    <xs:attribute name="csapat_IDREF" type="xs:integer"/>
    <xs:attribute name="csapat_ID" type="xs:integer"/>
    <xs:attribute name="kapitany_IDREF" type="xs:integer"/>
    <xs:attribute name="sportesemeny_IDREF" type="xs:integer"/>
    <xs:attribute name="sportesemeny_ID" type="xs:integer"/>
    <xs:attribute name="jatekvezeto_IDREF" type="xs:integer"/>
    <xs:attribute name="jatekvezeto_ID" type="xs:integer"/>

    <!--Összetett típusok definíciói-->
    <xs:complexType name="szuletesiadatok_tipus">
        <xs:sequence>
            <xs:element ref="szuletesihely"/>
            <xs:element ref="szuletesiido"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ember_tipus">
        <xs:sequence>
            <xs:element ref="nev"/>
            <xs:element name="szuletesiadatok" type="szuletesiadatok_tipus"/>
            <xs:element ref="allampolgarsag"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="poszt_tipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="kapus"/>
            <xs:enumeration value="védő"/>
            <xs:enumeration value="középpályás"/>
            <xs:enumeration value="támadó"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="jatekos_tipus">
        <xs:complexContent>
            <xs:extension base="ember_tipus">
                <xs:sequence>
                    <xs:element name="poszt" type="poszt_tipus" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute ref="jatekos_ID" use="required"/>
                <xs:attribute ref="csapat_IDREF" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="jatekosok_tipus">
        <xs:sequence>
            <xs:element name="jatekos" type="jatekos_tipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="csapat_tipus">
        <xs:sequence>
            <xs:element ref="nev"/>
            <xs:element ref="alapitaseve"/>
            <xs:element ref="edzo"/>
        </xs:sequence>
        <xs:attribute ref="csapat_ID" use="required"/>
        <xs:attribute ref="kapitany_IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="csapatok_tipus">
        <xs:sequence>
            <xs:element name="csapat" type="csapat_tipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="reszvetel_tipus">
        <xs:sequence>
            <xs:element ref="helyezes"/>
        </xs:sequence>
        <xs:attribute ref="sportesemeny_IDREF" use="required"/>
        <xs:attribute ref="csapat_IDREF" use="required"/>
    </xs:complexType>

    <xs:complexType name="reszvetelek_tipus">
        <xs:sequence>
            <xs:element name="reszvetel" type="reszvetel_tipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sportesemeny_tipus">
        <xs:sequence>
            <xs:element ref="sportag"/>
            <xs:element ref="helyszin"/>
            <xs:element ref="datum"/>
        </xs:sequence>
        <xs:attribute ref="sportesemeny_ID" use="required"/>
        <xs:attribute ref="jatekvezeto_IDREF"/>
    </xs:complexType>

    <xs:complexType name="sportesemenyek_tipus">
        <xs:sequence>
            <xs:element name="sportesemeny" type="sportesemeny_tipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="jatekvezeto_tipus">
        <xs:complexContent>
            <xs:extension base="ember_tipus">
                <xs:attribute ref="jatekvezeto_ID" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="jatekvezetok_tipus">
        <xs:sequence>
            <xs:element name="jatekvezeto" type="jatekvezeto_tipus" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!--Teljes séma-->
    <xs:element name="sportesemenyekadatrendszere">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jatekosok" type="jatekosok_tipus"/>
                <xs:element name="csapatok" type="csapatok_tipus"/>
                <xs:element name="reszvetelek" type="reszvetelek_tipus"/>
                <xs:element name="sportesemenyek" type="sportesemenyek_tipus"/>
                <xs:element name="jatekvezetok" type="jatekvezetok_tipus"/>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->
        <!--Primary Keys-->
        <xs:key name="jatekos_PK">
            <xs:selector xpath="jatekosok/jatekos"/>
            <xs:field xpath="@jatekos_ID"/>
        </xs:key>
        <xs:key name="csapat_PK">
            <xs:selector xpath="csapatok/csapat"/>
            <xs:field xpath="@csapat_ID"/>
        </xs:key>
        <xs:key name="sportesemeny_PK">
            <xs:selector xpath="sportesemenyek/sportesemeny"/>
            <xs:field xpath="@sportesemeny_ID"/>
        </xs:key>
        <xs:key name="jatekvezeto_PK">
            <xs:selector xpath="jatekvezetok/jatekvezeto"/>
            <xs:field xpath="@jatekvezeto_ID"/>
        </xs:key>

        <!--Foreign Keys-->
        <xs:keyref name="jcsapat_FK" refer="csapat_PK">
            <xs:selector xpath="jatekosok/jatekos"/>
            <xs:field xpath="@csapat_IDREF"/>
        </xs:keyref>
        <xs:keyref name="kapitany_FK" refer="jatekos_PK">
            <xs:selector xpath="csapatok/csapat"/>
            <xs:field xpath="@kapitany_IDREF"/>
        </xs:keyref>
        <xs:keyref name="rcsapat_FK" refer="csapat_PK">
            <xs:selector xpath="reszvetelek/reszvetel"/>
            <xs:field xpath="@csapat_IDREF"/>
        </xs:keyref>
        <xs:keyref name="sportesemeny_FK" refer="sportesemeny_PK">
            <xs:selector xpath="reszvetelek/reszvetel"/>
            <xs:field xpath="@sportesemeny_IDREF"/>
        </xs:keyref>
        <xs:keyref name="jatekvezeto_FK" refer="jatekvezeto_PK">
            <xs:selector xpath="sportesemenyek/sportesemeny"/>
            <xs:field xpath="@jatekvezeto_IDREF"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== SimonMarcell/K9IVJV_XMLGyak/XMLTaskK9IVJV/DOMParseK9IVJV/out/production/DOMParseK9IVJV/XMLK9IVJV.xml
<?xml version="1.0" encoding="utf-8"?>

<sportesemenyekadatrendszere xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                             xsi:noNamespaceSchemaLocation="XMLSchemaK9IVJV.xsd">
    <jatekosok>
        <jatekos jatekos_ID="01" csapat_IDREF="06">
            <nev>Takács Mihály</nev>
            <szuletesiadatok>
                <szuletesihely>Budapest</szuletesihely>
                <szuletesiido>1988-08-08</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="02" csapat_IDREF="02">
            <nev>Szekeres Róbert</nev>
            <szuletesiadatok>
                <szuletesihely>Budapest</szuletesihely>
                <szuletesiido>1988-09-30</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
            <poszt>támadó</poszt>
            <poszt>középpályás</poszt>
            <poszt>védő</poszt>
        </jatekos>
        <jatekos jatekos_ID="03" csapat_IDREF="01">
            <nev>Miksa Szilárd</nev>
            <szuletesiadatok>
                <szuletesihely>Debrecen</szuletesihely>
                <szuletesiido>1989-01-18</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
            <poszt>támadó</poszt>
            <poszt>középpályás</poszt>
            <poszt>védő</poszt>
        </jatekos>
        <jatekos jatekos_ID="04" csapat_IDREF="03">
            <nev>László Antal</nev>
            <szuletesiadatok>
                <szuletesihely>Markotabödöge</szuletesihely>
                <szuletesiido>1990-06-18</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="05" csapat_IDREF="04">
            <nev>Egyed Zoltán</nev>
            <szuletesiadatok>
                <szuletesihely>Debrecen</szuletesihely>
                <szuletesiido>1990-11-19</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
        </jatekos>
        <jatekos jatekos_ID="06" csapat_IDREF="05">
            <nev>Szalai Adrián</nev>
            <szuletesiadatok>
                <szuletesihely>Szeged</szuletesihely>
                <szuletesiido>1991-01-15</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="07" csapat_IDREF="01">
            <nev>Kapolcs Vilmos</nev>
            <szuletesiadatok>
                <szuletesihely>Budapest</szuletesihely>
                <szuletesiido>1991-02-26</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="08" csapat_IDREF="03">
            <nev>Apród Levente</nev>
            <szuletesiadatok>
                <szuletesihely>Debrecen</szuletesihely>
                <szuletesiido>1992-05-29</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="09" csapat_IDREF="06">
            <nev>Simon János</nev>
            <szuletesiadatok>
                <szuletesihely>Szeged</szuletesihely>
                <szuletesiido>1992-07-13</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="10" csapat_IDREF="02">
            <nev>Dobos Dezső</nev>
            <szuletesiadatok>
                <szuletesihely>Mikekarácsonyfa</szuletesihely>
                <szuletesiido>1992-08-26</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="11" csapat_IDREF="05">
            <nev>Bakos György</nev>
            <szuletesiadatok>
                <szuletesihely>Budapest</szuletesihely>
                <szuletesiido>1993-06-25</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="12" csapat_IDREF="04">
            <nev>Pintér Attila</nev>
            <szuletesiadatok>
                <szuletesihely>Ásványráró</szuletesihely>
                <szuletesiido>1993-10-18</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="13" csapat_IDREF="05">
            <nev>Nemes Vilmos</nev>
            <szuletesiadatok>
                <szuletesihely>Kerkabarabás</szuletesihely>
                <szuletesiido>1993-12-13</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="14" csapat_IDREF="02">
            <nev>Kerekes Ákos</nev>
            <szuletesiadatok>
                <szuletesihely>Miskolc</szuletesihely>
                <szuletesiido>1994-05-08</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="15" csapat_IDREF="01">
            <nev>Molnár Arnold</nev>
            <szuletesiadatok>
                <szuletesihely>Pécs</szuletesihely>
                <szuletesiido>1994-06-25</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="16" csapat_IDREF="03">
            <nev>Jónás Benedek</nev>
            <szuletesiadatok>
                <szuletesihely>Budapest</szuletesihely>
                <szuletesiido>1994-12-06</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="17" csapat_IDREF="06">
            <nev>Hajdú Gyula</nev>
            <szuletesiadatok>
                <szuletesihely>Chernelházadamonya</szuletesihely>
                <szuletesiido>1995-12-31</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
            <poszt>kapus</poszt>
            <poszt>támadó</poszt>
        </jatekos>
        <jatekos jatekos_ID="18" csapat_IDREF="04">
            <nev>Váradi Ádám</nev>
            <szuletesiadatok>
                <szuletesihely>Szeged</szuletesihely>
                <szuletesiido>1996-01-03</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
            <poszt>támadó</poszt>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="19" csapat_IDREF="04">
            <nev>Orosz Miklós</nev>
            <szuletesiadatok>
                <szuletesihely>Miskolc</szuletesihely>
                <szuletesiido>1996-07-23</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>kapus</poszt>
            <poszt>középpályás</poszt>
            <poszt>támadó</poszt>
        </jatekos>
        <jatekos jatekos_ID="20" csapat_IDREF="05">
            <nev>Budai Marcell</nev>
            <szuletesiadatok>
                <szuletesihely>Pókaszepetk</szuletesihely>
                <szuletesiido>1997-04-12</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>támadó</poszt>
        </jatekos>
        <jatekos jatekos_ID="21" csapat_IDREF="03">
            <nev>Csonka Antal</nev>
            <szuletesiadatok>
                <szuletesihely>Győr</szuletesihely>
                <szuletesiido>1997-07-08</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>középpályás</poszt>
        </jatekos>
        <jatekos jatekos_ID="22" csapat_IDREF="02">
            <nev>Halász Károly</nev>
            <szuletesiadatok>
                <szuletesihely>Kiskundorozsma</szuletesihely>
                <szuletesiido>1998-06-07</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
            <poszt>kapus</poszt>
            <poszt>támadó</poszt>
        </jatekos>
        <jatekos jatekos_ID="23" csapat_IDREF="01">
            <nev>Vincze Henrik</nev>
            <szuletesiadatok>
                <szuletesihely>Debrecen</szuletesihely>
                <szuletesiido>1998-09-01</szuletesiido>
            </szuletesiadatok>
            <allampolgarsag>magyar</allampolgarsag>
            <poszt>védő</poszt>
            <poszt>középpályás</poszt>
            <poszt>kapus</poszt>
        </jatekos>
        <jatekos jatekos_ID="24" csapat_IDREF="03">
            <nev>Pásztor Jakab</nev>
            <szuletesiadatok>
